//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t handle any exceptions coming from Rollback..
        /// </summary>
        internal static string DoesNotHandleAnyExceptionsComingFromRollback {
            get {
                return ResourceManager.GetString("DoesNotHandleAnyExceptionsComingFromRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should only be called when argument is bound.
        /// </summary>
        internal static string ShouldOnlyBeCalledWhenArgumentIsBound {
            get {
                return ResourceManager.GetString("ShouldOnlyBeCalledWhenArgumentIsBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity should never be executed. It is a dummy activity.
        /// </summary>
        internal static string ThisActivityShouldNeverBeExecutedItIsADummyActivity {
            get {
                return ResourceManager.GetString("ThisActivityShouldNeverBeExecutedItIsADummyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should only be called for non-empty bindings..
        /// </summary>
        internal static string ThisShouldOnlyBeCalledForNonEmptyBindings {
            get {
                return ResourceManager.GetString("ThisShouldOnlyBeCalledForNonEmptyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We always have an original transaction..
        /// </summary>
        internal static string WeAlwaysHaveAnOriginalTransaction {
            get {
                return ResourceManager.GetString("WeAlwaysHaveAnOriginalTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We shouldn&apos;t call Id unless we have a runtime argument..
        /// </summary>
        internal static string WeShouldNotCallIdUnlessWeHaveARuntimeArgument {
            get {
                return ResourceManager.GetString("WeShouldNotCallIdUnlessWeHaveARuntimeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We should only add records if we have a tracking provider..
        /// </summary>
        internal static string WeShouldOnlyAddRecordsIfWeHaveATrackingProvider {
            get {
                return ResourceManager.GetString("WeShouldOnlyAddRecordsIfWeHaveATrackingProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We should only try to track if we have a tracking provider..
        /// </summary>
        internal static string WeShouldOnlyTryToTrackIfWeHaveATrackingProvider {
            get {
                return ResourceManager.GetString("WeShouldOnlyTryToTrackIfWeHaveATrackingProvider", resourceCulture);
            }
        }
    }
}
